version: 0.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}-beta'
  package_version: '{version}-beta'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}-beta'
before_build:
- cmd: nuget restore
build:
  project: Cinegy.MXFstreamAnalyzer.sln
  verbosity: minimal
after_build:
- cmd: >-
    7z a MXFstreamAnalyzer-%APPVEYOR_BUILD_VERSION%-PDB.zip %APPVEYOR_BUILD_FOLDER%\Cinegy.MXFstreamAnalyzer\bin\release
    
    appveyor PushArtifact MXFstreamAnalyzer-%APPVEYOR_BUILD_VERSION%-PDB.zip